application/routes.py
import os

from flask import Blueprint, render_template, session, flash, redirect, url_for, request, abort, make_response, \
    send_file
from flask import current_app

from .forms import CN2SDForm, PRIMForm
from .algorithms.CN2_SD import initialize_CN2_SD
from .algorithms.PRIM import initialize_PRIM
import pandas as pd
from .algorithms.errors import UserInputError
import json
from .VizRank.main import VizRank

main_bp = Blueprint('main_bp', __name__,
                    template_folder='templates',
                    static_folder='static')


@main_bp.route('/', methods=['GET'])
def main():
    return render_template('index.html')


def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in ['csv']


@main_bp.route('/data_columns', methods=['POST'])
def data_columns():
    if 'input_file' not in request.files:
        abort(make_response('No file part', 400))
    file = request.files['input_file']
    # If user does not select file, browser also
    # submit an empty part without filename
    if file.filename == '':
        abort(make_response('No selected file', 400))
    # Check for extension
    if not allowed_file(file.filename):
        abort(make_response('File must be a csv', 400))
    # Read csv file from request
    input_data = pd.read_csv(file).dropna()
    info_columns = {}
    columns = list(input_data.columns)
    for col_name in columns:
        column = input_data[col_name]
        column = column.astype("category")
        levels = column.unique()
        info_columns[col_name] = list(levels)
    # current_app.logger.debug(info_columns, 'error')
    return json.dumps(info_columns, indent=2, allow_nan=False)


##############
# CN2 routes #
##############

@main_bp.route('/cn2', methods=['GET', 'POST'])
def cn2():
    form = CN2SDForm()
    if form.validate_on_submit():
        # Read input data file
        # Check if the post request has the file part
        if 'input_file' not in request.files:
            flash('No file part', 'danger')
            return redirect(request.url)
        file = request.files['input_file']
        # If user does not select file, browser also
        # submit an empty part without filename
        if file.filename == '':
            flash('No selected file', 'danger')
            return redirect(request.url)
        # Check for extension
        if not allowed_file(file.filename):
            flash('File must be a csv', 'danger')
            return redirect(request.url)
        # Read csv file from request
        input_data = pd.read_csv(file)
        # Check validity of parameters
        args = {"input_data": input_data.dropna(),
                "col_output": form.output_column.data,
                "positive_class": form.positive_class.data,
                "weight_method": form.weight_method.data}
        if form.gamma.data:
            args["gamma"] = form.gamma.data
        if form.max_expressions.data:
            args["max_exp"] = form.max_expressions.data
        if form.min_wracc.data:
            args["min_wracc"] = form.min_wracc.data
        try:
            CN2 = initialize_CN2_SD(**args)
        except UserInputError as error:
            flash(error.message, 'danger')
            return redirect(request.url)
        except KeyError as error:
            flash(f' Key error: {str(error)}', 'danger')
            return redirect(request.url)
        # Set session CN2 object
        session['CN2'] = CN2
        return redirect(url_for('main_bp.cn2_exec'))
    return render_template('cn2_main.html', form=form)


@main_bp.route('/cn2/exec', methods=['GET', 'POST'])
def cn2_exec():
    CN2 = session['CN2']
    end = False
    best_rule = None
    if request.method == 'POST':
        end, best_rule = CN2.do_step()
    # Choose cols to show
    data, cols = prepare_data_CN2(CN2, best_rule, end)
    return render_template('cn2_exec.html', rule_list=CN2.rule_list, end=end, data=data, cols=cols,
                           col_output=CN2.col_output)


def prepare_data_CN2(CN2, last_rule, end_cn2):
    """
    Prepares data to be sent to template. First, it selects
    the columns that will be in the graph via VizRank of checking
    last rule found. Then, it also adds the output column and
    the weights column. Finally, it transforms the data in those
    columns to JSON format.
    :param end_cn2:
    :param CN2: a CN2 algorithm object
    :param last_rule: last rule found
    :return: formatted data, ready to be send to template and columns selected
    """
    cols = []
    if last_rule and not end_cn2:
        if len(last_rule.antecedents) > 1:
            var1 = last_rule.antecedents[0].variable
            var2 = last_rule.antecedents[1].variable
            if var1 != var2:
                cols = [var1, var2]
            else:
                actual_len = 2
                end = False
                while not end and actual_len < len(last_rule.antecedents):
                    var2 = last_rule.antecedents[actual_len].variable
                    actual_len += 1
                    if var1 != var2:
                        cols = [var1, var2]
                        end = True
                if not end:
                    cols, _ = VizRank(input_data=CN2.current_data.drop(["weight_times", "weights", "subgroups"], axis=1),
                                      col_output=CN2.col_output,
                                      fixed_col=var1
                                      )
        elif len(last_rule.antecedents) == 1:
            cols, _ = VizRank(input_data=CN2.current_data.drop(["weight_times", "weights", "subgroups"], axis=1),
                              col_output=CN2.col_output,
                              fixed_col=last_rule.antecedents[0].variable
                              )
    else:
        cols, _ = VizRank(input_data=CN2.current_data.drop(["weight_times", "weights", "subgroups"], axis=1),
                          col_output=CN2.col_output
                          )
    data = CN2.current_data
    cols_data = cols + ["weights", CN2.col_output]
    if end_cn2:
        cols_data += ["subgroups"]
    data = data[cols_data]
    # Prepare data por d3
    chart_data = data.to_dict(orient='records')
    chart_data = json.dumps(chart_data, indent=2)
    data = {'chart_data': chart_data}
    return data, cols


###############
# PRIM routes #
###############

@main_bp.route('/prim', methods=['GET', 'POST'])
def prim():
    form = PRIMForm()
    if form.validate_on_submit():
        # Read input data file
        # Check if the post request has the file part
        if 'input_file' not in request.files:
            flash('No file part', 'danger')
            return redirect(request.url)
        file = request.files['input_file']
        # If user does not select file, browser also
        # submit an empty part without filename
        if file.filename == '':
            flash('No selected file', 'danger')
            return redirect(request.url)
        # Check for extension
        if not allowed_file(file.filename):
            flash('File must be a csv', 'danger')
            return redirect(request.url)
        # Read csv file from request
        input_data = pd.read_csv(file)
        ordinal_columns = {}
        if len(form.ordinal_columns.data) > 0:
            # Names separated by comma
            ordinal_col_names = [x.strip() for x in form.ordinal_columns.data.split(',')]
            # Ordered column values lists separated by ;
            ordinal_col_values = form.ordinal_columns_values.data.split(';')
        try:
            if len(form.ordinal_columns.data) > 0:
                for i, ord_col in enumerate(ordinal_col_names):
                    # We convert string values to column type if necessary
                    ordinal_columns[ord_col] = [type(input_data[ord_col][0])(x.strip())
                                                for x in ordinal_col_values[i].split(',')]
            args = {"input_data": input_data.dropna(),
                    "col_output": form.output_column.data,
                    "positive_class": form.positive_class.data,
                    "ordinal_columns": ordinal_columns}
            if form.alpha.data:
                args["alpha"] = form.alpha.data
            if form.threshold_global.data:
                args["threshold_global"] = form.threshold_global.data
            if form.threshold_box.data:
                args["threshold_box"] = form.threshold_box.data
            if form.min_mean.data:
                args["min_mean"] = form.min_mean.data
            PRIM = initialize_PRIM(**args)
        except UserInputError as error:
            flash(error.message, 'danger')
            return redirect(request.url)
        except KeyError as error:
            flash(f' Key error: {str(error)}', 'danger')
            return redirect(request.url)
        # Set session PRIM object and variables
        session['PRIM'] = PRIM
        session['end_PRIM'] = False
        return redirect(url_for('main_bp.prim_exec'))
    return render_template('prim_main.html', form=form)


def prepare_data_PRIM(PRIM, end_prim):
    """
    Prepares data to be sent to template. First, it selects
    the columns that will be in the graph via VizRank of checking
    boundaries in current box. Then, it also adds the output column
    and the bitmap column for box data. Finally, it transforms the data
    in those columns to JSON format.
    :param end_prim:
    :param PRIM: an object of PRIM's algorithm
    :return: formatted data, ready to be send to template and columns selected
    """
    # Choose cols
    cols = []
    if end_prim:
        input_data = PRIM.input_data.drop(["subgroup"], axis=1)
    else:
        input_data = PRIM.current_data
    if len(PRIM.current_box.boundary_list) > 0:
        if len(PRIM.current_box.boundary_list) > 1:
            var1 = PRIM.current_box.boundary_list[-1].variable_name

application/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap and JQuery -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!--  Custom styles -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main_styles.css') }}">

    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <a class="navbar-brand" href="{{ url_for('main_bp.main') }}">Visualización</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main_bp.prim') }}">PRIM</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main_bp.cn2') }}">CN2-SD</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main_bp.examples_main') }}">Datasets</a>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container">
        {% with messages = get_flashed_messages(with_categories=True) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="alert alert-{{ category }}">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
        {% block content %} {% endblock %}
    </div>


    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <script type="text/javascript">
    // Function so that the file selected is shown on the file browser
    $('.custom-file input').change(function (e) {
        if (e.target.files.length) {
            $(this).siblings('.custom-file-label').html(e.target.files[0].name);
        }
    });
    </script>
    <script>
        var col_options = {};
        document.getElementById('input_file').onchange = function(e) {
            e.preventDefault();
            var myFormData = new FormData();
            myFormData.append('input_file', this.files[0]);

            $.ajax({
              url: "{{ url_for('main_bp.data_columns') }}",
              type: 'POST',
              processData: false, // important
              contentType: false, // important
              dataType : 'json',
              data: myFormData,
              success : function(data){
                    //console.log(data);
                    col_options = data;
                    var col_output_element = document.getElementById('output_column');
                    // Eliminate options that were there before
                    col_output_element.options.length = 0;
                    for(var col in col_options){
                        col_output_element.add(new Option(col, col));
                    }
                    col_output_element.onchange = function(){
                        const selected = col_output_element.options[col_output_element.selectedIndex].text;
                        var positive_class_element = document.getElementById('positive_class');
                        positive_class_element.options.length = 0;
                        col_options[selected].forEach(function (item, index) {
                          positive_class_element.add(new Option(item, item));
                        });
                        // Ordinal columns may have changed
                        $('#ordinal_cols_number').val("");
                        $('#ordinal_cols_number').keyup();
                    };
                    col_output_element.onchange();
                    // To show in PRIM the ordinal columns
                    $("#ordinal_cols_number_div").attr('hidden',false);
               },
              error: function (xhr, textStatus, errorThrown) {
			    alert(`An error has occurred: ${textStatus}, ${errorThrown}, ${xhr["responseText"]}`);
			    var col_output_element = document.getElementById('output_column');
			    col_output_element.options.length = 0;
			    var positive_class_element = document.getElementById('positive_class');
			    positive_class_element.options.length = 0;
			    // To hide in PRIM the ordinal columns
			    $("#ordinal_cols_number_div").attr('hidden',true);
			  }
            });
        };
    </script>
    {% block additional_js %}
    {% endblock %}
</body>
</html>

application/templates/base_graphics.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap and JQuery -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <!--  Custom styles -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main_styles.css') }}">
    <!-- D3 js for graphics -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/5.16.0/d3.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/d3-legend/2.24.0/d3-legend.min.js"></script>
    <!-- JQuery color and color mixer for mixing colors -->
    <script src="https://code.jquery.com/color/jquery.color-2.2.0.min.js" integrity="sha256-aSe2ZC5QeunlL/w/7PsVKmV+fa0eDbmybn/ptsKHR6I=" crossorigin="anonymous"></script>
    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <a class="navbar-brand" href="{{ url_for('main_bp.main') }}">Visualización</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main_bp.prim') }}">PRIM</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main_bp.cn2') }}">CN2-SD</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main_bp.examples_main') }}">Datasets</a>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container">
        {% with messages = get_flashed_messages(with_categories=True) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="alert alert-{{ category }}">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
        {% block content %} {% endblock %}
    </div>


    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>
</html>

application/templates/cn2_exec.html
{% extends "base_graphics.html" %}

{% block title %}
CN2-SD
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col">
            <h2>Executing CN2-SD </h2>
            {% if end %}
                <h3> It is finished! </h3> <br>
                <p>The colors now represent the subgroups and the shapes represent the class. If an element belong to multiple groups, a mixed color is shown. The subgroup colors are:</p>
                <div id="legend_subgroups">
                    <svg></svg>
                </div>
            {% else %}
                 <div class="content-section">
                     <form method="POST" action="" enctype="multipart/form-data">
                        <div class="form-group">
                            <input class="btn btn-outline-info" id="submit" name="submit" type="submit" value="Do step!">
                        </div>
                    </form>
                </div>
            {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="col-12" id="chartArea">
            <svg ></svg>
        </div>
        <div class="col-12">
            <h3>Rules found:</h3>
            <table class="table table-hover table-responsive">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Rule</th>
                        <th scope="col">WRAcc</th>
                        <th scope="col">Coverage</th>
                        <th scope="col">Support</th>
                        <th scope="col">Significance</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for rule in rule_list %}
                        <tr>
                            <th scope="row">{{ loop.index }}</th>
                            <td>{{ rule }}</td>
                            <td>{{ "%.4f"|format(rule.wracc) }}</td>
                            <td>{{ "%.4f"|format(rule.coverage) }}</td>
                            <td>{{ "%.4f"|format(rule.support) }}</td>
                            <td>{{ "%.4f"|format(rule.significance) }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <script src="{{ url_for('static', filename='js/graphics.js') }}"></script>
    <script src="{{ url_for('static', filename='js/color_mixer.js') }}"></script>
    <script>
        const graphData = {{ data.chart_data | safe }};
        const cols = {{ cols | safe }};
        const col_output = '{{ col_output | safe }}';
        const end = ('{{ end }}' == 'True');
        const rule_list = [];
        {% for rule in rule_list %}
        rule_list.push(`{{ rule | safe }}`);
        {% endfor %}
        var algorithm = {
            "name": "CN2"
        }
        const resize = () => redraw(graphData,cols,col_output,algorithm,end,rule_list);
        resize();
        window.onresize = resize;
    </script>
{% endblock %}

application/templates/cn2_main.html
{% extends "base.html" %}

{% block title %}
CN2-SD
{% endblock %}

{% block content %}

    <div class="row">
        <div class="col col-lg-8">
            <div class="content-section">
                <form method="POST" action="" enctype="multipart/form-data">
                    {{ form.hidden_tag() }}
                    <fieldset class="form-group">
                        <legend class="border-bottom mb-4"> Parameters for the algorithm </legend>
                        <div class="custom-file mb-2">
                            {% if form.input_file.errors %}
                                {{ form.input_file(class="custom-file-input is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.input_file.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.input_file(class="custom-file-input") }}
                            {% endif %}
                            {{ form.input_file.label(class="custom-file-label") }}
                        </div>
                        <div class="form-group">
                            {{ form.output_column.label(class="form-control-label") }}
                            {% if form.output_column.errors %}
                                {{ form.output_column(class="form-control is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.output_column.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.output_column(class="form-control") }}
                            {% endif %}
                        </div>
                        <div class="form-group">
                            {{ form.positive_class.label(class="form-control-label") }}
                            {% if form.positive_class.errors %}
                                {{ form.positive_class(class="form-control is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.positive_class.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.positive_class(class="form-control") }}
                            {% endif %}
                        </div>
                        <div class="form-group">
                            {{ form.max_expressions.label(class="form-control-label") }}
                            {% if form.max_expressions.errors %}
                                {{ form.max_expressions(class="form-control is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.max_expressions.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.max_expressions(class="form-control") }}
                            {% endif %}
                        </div>
                        <div class="form-group">
                            {{ form.min_wracc.label(class="form-control-label") }}
                            {% if form.min_wracc.errors %}
                                {{ form.min_wracc(class="form-control is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.min_wracc.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.min_wracc(class="form-control") }}
                            {% endif %}
                        </div>
                        <div class="form-group">
                            {{ form.weight_method.label(class="form-control-label") }}
                            {% if form.weight_method.errors %}
                                {{ form.weight_method(class="form-control is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.weight_method.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.weight_method(class="form-control") }}
                            {% endif %}
                        </div>
                        <div class="form-group">
                            {{ form.gamma.label(class="form-control-label") }}
                            {% if form.gamma.errors %}
                                {{ form.gamma(class="form-control is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.gamma.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.gamma(class="form-control") }}
                            {% endif %}
                        </div>
                    </fieldset>
                    <div class="form-group">
                        {{ form.submit(class="btn btn-outline-info") }}
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

application/templates/examples.html
{% extends "base.html" %}

{% block title %}
Datasets
{% endblock %}

{% block content %}
<h1>Example datasets: </h1>
{% for key, item in titles_descriptions.items() %}
    <h3> {{ item[0] }}</h3>
    <p> {{ item[1] }} </p>
    <form method="GET" action="{{ url_for('main_bp.examples_download', filename=key) }}">
        <div class="form-group">
            <input class="btn btn-outline-info" id="submit" name="submit" type="submit" value="Download">
        </div>
    </form>
{% endfor %}
{% endblock %}

application/templates/index.html
{% extends "base.html" %}

{% block title %}
Main page
{% endblock %}

{% block content %}
    <h1>Welcome! </h1>
    <p>
        This website offers the possibility of executing and visualizing subgroup algorithms step by step. For now, the
        possibilities are:
    </p>
    <h2> CN2-SD</h2>
    <p>
        This algorithm consists on a modification of the classification rule learner algorithm CN2, adapted to subgroup
        discovery, with extra features like weighted relative accuracy. It is based on an article that can be found in
        <a href="http://www.jmlr.org/papers/volume5/lavrac04a/lavrac04a.pdf">here</a>. The step by step execution of this algorithm
        lets you observe the data in a dynamic scatterplot whose axes will be selected taking into account the rules that
        are being found (that describe subgroups). A slight modification of
        <a href="https://www.researchgate.net/publication/225719533_VizRank_Data_Visualization_Guided_by_Machine_Learning"
        >VizRank</a> is used to choose the best two axes (for class separation) in the first visualization. Also, the points
        in the graph will decrease in size, depending on each point's "weight" (used in the algorithm). To start
        the execution of this algorithm with your own data, click on the next button: <br>

        <a class="btn btn-outline-info mt-2" href="{{ url_for('.cn2') }}"> Start! </a>

    </p>

    <h2> PRIM </h2>
    <p>
        This algorithm is the patient rule induction method and the article in which the implementation is based can be
        found <a href="http://statweb.stanford.edu/~jhf/ftp/prim.pdf"> here</a>. It is designed to find (greedily) boxes
        that characterise different subgroups in the data. These boxes are built by an iterative top-down peeling process,
        a bottom-up pasting technique and a check for redundant variables. The step execution of this
        algorithm lets you observe the data in a dynamic scatterplot whose axes will be selected taking into account the
        variables selected to peel in the top-down process. Also, a slight modification of
        <a href="https://www.researchgate.net/publication/225719533_VizRank_Data_Visualization_Guided_by_Machine_Learning"
        >VizRank</a> is used to choose the best two axes (for class separation) in the first visualization of each step.
        To start the execution of this algorithm with your own data, click on the next button: <br>

        <a class="btn btn-outline-info mt-3" href="{{ url_for('.prim') }}"> Start! </a>

    </p>

    <h3>Example datasets</h3>
    <p>
        Also, we offer a few examples of datasets ready to download for you to try the algorithms. Click the button
        to see them: <br>
        <a class="btn btn-outline-info mt-3" href="{{ url_for('.examples_main') }}"> Examples </a>

    </p>

    <footer class="footer">
        Developed by Martín Sánchez-Pedreño Sánchez. <a href="https://github.com/martinsps/Visualization_SD">Source code in Github.</a>
    </footer>

{% endblock %}